apiVersion: apps/v1
kind: Deployment
metadata:
  name: db-deployment
  labels:
    app: db
spec:
  replicas: 1
  selector:
    matchLabels:
      app: db
  template:
    metadata:
      labels:
        app: db
    spec:
      containers:
      - name: mongo
        image: mongo:5.0-focal
        ports:
          - containerPort: 27017
        env:
        - name:  MONGO_INITDB_ROOT_USERNAME
          valueFrom:
            secretKeyRef:
              key: MONGO_INITDB_ROOT_USERNAME
              name:  mongo-secret
        - name:  MONGO_INITDB_ROOT_PASSWORD
          valueFrom:
            secretKeyRef:
              key: MONGO_INITDB_ROOT_PASSWORD
              name: mongo-secret
        volumeMounts:
        - name: "mongodatabase"
          mountPath: "/var/lib/mongo/data"
      volumes:
      - name: "mongodatabase"
        persistentVolumeClaim:
          claimName: "mongo-pvc"
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: db
  name: db-service
spec:
  ports:
  - port: 27017
    targetPort: 27017
    protocol: TCP
  selector:
    app: db
