# docker compose du projet pfe
version: "3"
services:
  app:
    build: .
    image: marvel:v1
    restart: always
    environment:
      - MONGO_URI=mongodb://${MONGO_INITDB_ROOT_USERNAME}:${MONGO_INITDB_ROOT_PASSWORD}@db/local?authSource=admin
    ports:
      - 5000:5000   
  db:
    image: mongo:5.0-focal
    restart: always
    volumes:
      - mongodatabase:/data/db
    environment:
      - MONGO_INITDB_ROOT_PASSWORD=${MONGO_INITDB_ROOT_PASSWORD}
      - MONGO_INITDB_ROOT_USERNAME=${MONGO_INITDB_ROOT_USERNAME}
  
volumes:
    mongodatabase: