# docker compose du projet pfe
version: "3"
services:
  app:
    image: marvel:v1
    restart: always
    environment:
      - MONGO_URI=mongodb://db/library # lien de connexion vers la base de donnée
    ports:
      - 5000:5000   
  db:
    image: mongo:5.0-focal
    env_file:
      - ./.env
    restart: always
    environment:
      - MONGO_INITDB_ROOT_USERNAME=mongouser
      - MONGODB_INITDB_ROOT_PASSWORD=mongopassword

 
    
