# docker compose du projet pfe
version: "3"
services:
  app:
    image: marvel:v1
    restart: always
    environment:
      - MONGODB_CONNSTRING=mongodb+srv://Marvel:Password123@cluster0.4eo8ulb.mongodb.net/test?retryWrites=true&w=majority # lien de connexion vers la base de donnée
    ports:
      - 5000:5000   
  db:
    image: mongo:focal
    restart: always
    environment:
      - MONGODB_ADMINUSERNAME=Marvel
      - MONGODB_ADMINPASSWORD=Password123


 
    
