version: "3"
services:
  projet-pfe:
    image: marvel:v1
    ports:
      - "5000:5000"
    depends_on:
      - Flask-mongo
  Flask-mongo:
    image: mongo
    environment:
      - MONGODB_CONNSTRING=mongodb+srv://Marvel:Password123@cluster0.4eo8ulb.mongodb.net/test?retryWrites=true&w=majority

 
    
        

 



  

  