---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: projetpfe
  namespace: flux-system
spec:
  chart:
    spec:
      chart: projetpfe
      reconcileStrategy: ChartVersion
      sourceRef:
        kind: GitRepository
        name: projet-pfe
  interval: 1m0s
  releaseName: projetpfe
  targetNamespace: flux-system
