---
apiVersion: image.toolkit.fluxcd.io/v0.21.0
kind: ImageUpdateAutomation
metadata:
  name: flux-system
  namespace: flux-system
spec:
  git:
    checkout:
      ref:
        branch: main
    commit:
      author:
        email: marvellck@users.noreply.github.com
        name: marvellck
      messageTemplate: '{{range .Updated.Images}}{{println .}}{{end}}'
    push:
      branch: main
  interval: 1m0s
  sourceRef:
    kind: GitRepository
    name: projet-pfe
  update:
    path: ./
    strategy: Setters

