apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: app
  name: app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: app
  strategy: {}
  template:
    metadata:
      labels:
        app: app
    spec:
      containers:
      - image: ghcr.io/marvellck/marvel
        name: marvel
        ports:
          - containerPort: 5000
        resources: {}
status: {}


