apiVersion: apps/v1
kind: Deployment
metadata:
  name: db-deployment
  labels:
    app: db
spec:
  replicas: 3
  selector:
    matchLabels:
      app: db
  template:
    metadata:
      labels:
        app: db
    spec:
      containers:
      - name: mongo
        image: mongo:5.0-focal
        ports:
          - containerPort: 27017
        env:
       # - name: MONGO_URI
         # value: MONGO_URI=mongodb://${SECRET_USERNAME}:${SECRET_PASSWORD}@db/local?authSource=admin
        - name: SECRET_USERNAME
          valueFrom:
            secretKeyRef:
              name: db-secret
              key: username
        - name: SECRET_PASSWORD
          valueFrom:
            secretKeyRef:
              name: db-secret
              key: password
        volumeMounts:
        - name: "mongodatabase"
          mountPath: "/var/lib/mongo/data"
      volumes:
      - name: "mongodatabase"
        persistentVolumeClaim:
          claimName: "mongo-pvc"

      
      
      
      
      
---


apiVersion: v1
kind: Service
metadata:
  name: db-service
spec:
  type: ClusterIP
  selector:
    app.kubernetes.io/name: db
  ports:
    - name: mongo-svc
      port: 27017
      protocol: TCP
