apiVersion: apps/v1
kind: Deployment
metadata:
  name: db-deployment
  labels:
    app: db
spec:
  replicas: 1
  selector:
    matchLabels:
      app: db
  template:
    metadata:
      labels:
        app: db
    spec:
      containers:
      - name: mongo
        image: mongo:5.0-focal
        ports:
          - containerPort: 27017
        volumeMounts:
        - name: "mongodatabase"
          mountPath: "/var/lib/mongo/data"
      volumes:
      - name: "mongodatabase"
        persistentVolumeClaim:
          claimName: "mongo-pvc"

      
      
      
      
      
---


apiVersion: v1
kind: Service
metadata:
  name: db-service
spec:
  type: ClusterIP
  selector:
    app: db
  ports:
    - name: mongo-svc
      port: 27017
      protocol: TCP
