name: Create cluster

on: 
  push:
    branches:
      - main
       


jobs:
  create-cluster:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        
      - name: Create K8s Kind Cluster
        uses: helm/kind-action@v1.3.0
        with:
          path: ./kind-cluster.yaml 

      - name: Test
        run: |
          kubectl cluster-info
          kubectl get nodes
     
