name: Create cluster

on: 
  push:
    branches:
      - main
       
jobs:
  create-cluster:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        
      - name: Create K8s Kind Cluster
        uses: /home/urnga/Bureau/projet-pfe/.github/workflows/kind-cluster.yaml
      - name: Test
        run: |
          kubectl cluster-info
          kubectl get nodes
