name: Create cluster

on : 
   pull_request:
    branches:
      - main


jobs:
  create-cluster:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        
      - name: Create K8s Kind Cluster
        uses: helm/kind-action@v1.3.0

      - name: Test
        run: |
          kubectl cluster-info
          kubectk get nodes
     
