name: Create cluster

on: 
  push:
    branches:
      - main
       


jobs:
  create-cluster:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        
      - name: Create K8s Kind Cluster
        uses: ./kind-cluster.yaml
        run: |
          kind create cluster --config kind-cluster.yaml

      - name: Test
        run: |
          kubectl cluster-info
          kubectl get nodes
     
