name: FLUX CD

on: push

jobs:
  fluxctl:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Setup Kubernetes
        uses: engineerd/setup-kind@v0.3.0
      - name: Setup fluxctl
        uses: fluxcd/fluxctl-action@master
      - name: Install Flux
        run: |
          kubectl create ns flux
          fluxctl install \
          --git-path= ../../K8s \
          --git-branch=main \
          --git-readonly=true \
          --registry-disable-scanning=true \
          --git-email=Marvellck@users.noreply.github.com \
          --git-url=git@github.com:Marvellck/projet-pfe.git \
          --namespace=flux | kubectl apply -f -
      - name: Verify install
        run: kubectl -n flux rollout status deploy/flux --timeout=1m
      - name: Sync git with cluster
        env:
          FLUX_FORWARD_NAMESPACE: flux
        run: fluxctl sync
      - name: Verify sync
        run: kubectl get ns | grep test
